export { default as NavBar } from "./NavBar"
export { default as Home } from "./Home"
export { default as Skills } from "./Skills"
export { default as Projects } from "./projects"
export { default as Footer } from "./Footer"